// <auto-generated />
using System;
using CryptoMarketApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CryptoMarketApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("CryptoMarketApi.Entities.Coin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoinGeckoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoinName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CoinSymbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoinGeckoId = "bitcoin",
                            CoinName = "Bitcoin",
                            CoinSymbol = "BTC"
                        },
                        new
                        {
                            Id = 2,
                            CoinGeckoId = "monero",
                            CoinName = "Monero",
                            CoinSymbol = "MON"
                        },
                        new
                        {
                            Id = 3,
                            CoinGeckoId = "ethereum",
                            CoinName = "Ethereum",
                            CoinSymbol = "ETH"
                        },
                        new
                        {
                            Id = 4,
                            CoinGeckoId = "solana",
                            CoinName = "Solana",
                            CoinSymbol = "SOL"
                        });
                });

            modelBuilder.Entity("CryptoMarketApi.Entities.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoinId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CoinId");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("CryptoMarketApi.Entities.Price", b =>
                {
                    b.HasOne("CryptoMarketApi.Entities.Coin", "Coin")
                        .WithMany("Prices")
                        .HasForeignKey("CoinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coin");
                });

            modelBuilder.Entity("CryptoMarketApi.Entities.Coin", b =>
                {
                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
